package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"
	"fmt"
	"gitanalytics/server/auth"
	"gitanalytics/server/graph/generated"
	"gitanalytics/server/graph/model"

	"github.com/google/uuid"
)

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	// Logic:
	// 1. Insert Project into projects table via Hasura
	// 2. Return the created project

	var createProject struct {
		InsertProjectsOne struct {
			ID            string  `json:"id"`
			Name          string  `json:"name"`
			CompanyID     string  `json:"company_id"`
			ManagerUserID string  `json:"manager_user_id"`
			Description   *string `json:"description"`
			RepoURL       *string `json:"repo_url"`
			CreatedAt     string  `json:"created_at"`
		} `json:"insert_projects_one"`
	}

	// We need to fetch the company_id for the manager first, or assume it's passed?
	// The schema input doesn't have companyId, only managerUserId.
	// We should probably fetch the user's company_id from Hasura.

	var userCompany struct {
		UsersByPk struct {
			CompanyID string `json:"company_id"`
		} `json:"users_by_pk"`
	}

	err := r.HasuraClient.Request(`
		query GetUserCompany($id: uuid!) {
			users_by_pk(id: $id) {
				company_id
			}
		}
	`, map[string]interface{}{"id": input.ManagerUserID}, &userCompany)

	if err != nil {
		return nil, fmt.Errorf("failed to fetch manager company: %w", err)
	}
	if userCompany.UsersByPk.CompanyID == "" {
		return nil, errors.New("manager does not belong to a company")
	}

	variables := map[string]interface{}{
		"name":          input.Name,
		"managerUserId": input.ManagerUserID,
		"companyId":     userCompany.UsersByPk.CompanyID,
		"description":   input.Description,
		"repoUrl":       input.RepoURL,
	}

	err = r.HasuraClient.Request(`
		mutation CreateProject(
			$name: String!, 
			$managerUserId: uuid!, 
			$companyId: uuid!,
			$description: String,
			$repoUrl: String
		) {
			insert_projects_one(object: {
				name: $name,
				manager_user_id: $managerUserId,
				company_id: $companyId,
				description: $description,
				repo_url: $repoUrl
			}) {
				id
				name
				company_id
				manager_user_id
				description
				repo_url
				created_at
			}
		}
	`, variables, &createProject)

	if err != nil {
		return nil, fmt.Errorf("failed to create project: %w", err)
	}

	proj := createProject.InsertProjectsOne
	return &model.Project{
		ID:            proj.ID,
		Name:          proj.Name,
		CompanyID:     proj.CompanyID,
		ManagerUserID: proj.ManagerUserID,
		Description:   proj.Description,
		RepoURL:       proj.RepoURL,
		CreatedAt:     proj.CreatedAt,
	}, nil
}

// AssignMember is the resolver for the assignMember field.
func (r *mutationResolver) AssignMember(ctx context.Context, input model.AssignMemberInput) (*model.ProjectMember, error) {
	// Logic:
	// 1. Insert Project Member record via Hasura
	// 2. Return the created member record

	var assignMember struct {
		InsertProjectMembersOne struct {
			ID        string `json:"id"`
			ProjectID string `json:"project_id"`
			UserID    string `json:"user_id"`
			Role      string `json:"role"`
			JoinedAt  string `json:"joined_at"`
		} `json:"insert_project_members_one"`
	}

	variables := map[string]interface{}{
		"projectId": input.ProjectID,
		"userId":    input.UserID,
		"role":      input.Role.String(),
	}

	err := r.HasuraClient.Request(`
		mutation AssignMember($projectId: uuid!, $userId: uuid!, $role: member_role!) {
			insert_project_members_one(object: {
				project_id: $projectId,
				user_id: $userId,
				role: $role
			}) {
				id
				project_id
				user_id
				role
				joined_at
			}
		}
	`, variables, &assignMember)

	if err != nil {
		// Handle potential duplicate or constraints? Hasura will return error, we wrap it.
		return nil, fmt.Errorf("failed to assign member: %w", err)
	}

	member := assignMember.InsertProjectMembersOne

	// Convert string role back to enum if validated, but here we just cast
	role := model.ProjectMemberRole(member.Role)

	return &model.ProjectMember{
		ID:        member.ID,
		ProjectID: member.ProjectID,
		UserID:    member.UserID,
		Role:      role,
		JoinedAt:  member.JoinedAt,
	}, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, input model.DeleteProjectInput) (*model.DeleteProjectResponse, error) {
	// Logic:
	// 1. Delete the project from projects table via Hasura
	// 2. Hasura will cascade delete related records (project_members, git_commits, etc.)
	// 3. Return success response

	var deleteProject struct {
		DeleteProjectsByPk struct {
			ID string `json:"id"`
		} `json:"delete_projects_by_pk"`
	}

	variables := map[string]interface{}{
		"projectId": input.ProjectID,
	}

	err := r.HasuraClient.Request(`
		mutation DeleteProject($projectId: uuid!) {
			delete_projects_by_pk(id: $projectId) {
				id
			}
		}
	`, variables, &deleteProject)

	if err != nil {
		return &model.DeleteProjectResponse{
			Success: false,
			Message: fmt.Sprintf("Failed to delete project: %v", err),
		}, nil
	}

	if deleteProject.DeleteProjectsByPk.ID == "" {
		return &model.DeleteProjectResponse{
			Success: false,
			Message: "Project not found",
		}, nil
	}

	return &model.DeleteProjectResponse{
		Success: true,
		Message: "Project deleted successfully",
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.LoginResponse, error) {
	var query struct {
		Users []struct {
			ID           string  `json:"id"`
			Email        string  `json:"email"`
			PasswordHash string  `json:"password_hash"`
			FullName     *string `json:"full_name"`
			CompanyID    string  `json:"company_id"`
			Company      struct {
				AdminUserID *string `json:"admin_user_id"`
			} `json:"company"`
		} `json:"users"`
	}

	variables := map[string]interface{}{
		"email": email,
	}

	err := r.HasuraClient.Request(`
		query GetUserByEmail($email: String!) {
			users(where: {email: {_eq: $email}}, limit: 1) {
				id
				email
				password_hash
				full_name
				company_id
				company {
					admin_user_id
				}
			}
		}
	`, variables, &query)

	if err != nil {
		return nil, fmt.Errorf("failed to query user: %w", err)
	}

	if len(query.Users) == 0 {
		return nil, errors.New("Invalid email or password")
	}

	user := query.Users[0]

	if !auth.CheckPasswordHash(password, user.PasswordHash) {
		return nil, errors.New("Invalid email or password")
	}

	roles := []string{"user"}
	defaultRole := "user"

	if user.Company.AdminUserID != nil && *user.Company.AdminUserID == user.ID {
		roles = append(roles, "admin")
		defaultRole = "admin"
	}

	// Check if user is a manager (optional, logic from auth.go)
	var managerQuery struct {
		ProjectsAggregate struct {
			Aggregate struct {
				Count int `json:"count"`
			} `json:"aggregate"`
		} `json:"projects_aggregate"`
	}
	managerVars := map[string]interface{}{
		"userId": user.ID,
	}
	_ = r.HasuraClient.Request(`
		query CheckManager($userId: uuid!) {
			projects_aggregate(where: {manager_user_id: {_eq: $userId}}) {
				aggregate {
					count
				}
			}
		}
	`, managerVars, &managerQuery)
	// Ignore error, treating as not manager if query fails (or handle better)
	if managerQuery.ProjectsAggregate.Aggregate.Count > 0 {
		roles = append(roles, "manager")
		if defaultRole == "user" {
			defaultRole = "manager"
		}
	}

	userIDUUID, err := uuid.Parse(user.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id uuid: %w", err)
	}

	token, err := auth.GenerateJWT(userIDUUID, roles, defaultRole)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	return &model.LoginResponse{
		Token: token,
		User: &model.User{
			ID:        user.ID,
			Email:     user.Email,
			FullName:  user.FullName,
			CompanyID: user.CompanyID,
		},
	}, nil
}

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, companyName string, licenseKey string, adminEmail string, password string, fullName *string) (*model.SignupResponse, error) {
	// 1. Check License
	var checkLicense struct {
		Companies []struct {
			ID string `json:"id"`
		} `json:"companies"`
	}
	err := r.HasuraClient.Request(`
		query CheckLicense($key: String!) {
			companies(where: {license_key: {_eq: $key}}) { id }
		}
	`, map[string]interface{}{"key": licenseKey}, &checkLicense)
	if err != nil {
		return nil, err
	}
	if len(checkLicense.Companies) > 0 {
		return nil, errors.New("License key already in use")
	}

	// 2. Check Email
	var checkEmail struct {
		Users []struct {
			ID string `json:"id"`
		} `json:"users"`
	}
	err = r.HasuraClient.Request(`
		query CheckEmail($email: String!) {
			users(where: {email: {_eq: $email}}) { id }
		}
	`, map[string]interface{}{"email": adminEmail}, &checkEmail)
	if err != nil {
		return nil, err
	}
	if len(checkEmail.Users) > 0 {
		return nil, errors.New("Email already registered")
	}

	// 3. Hash Password
	passwordHash, err := auth.HashPassword(password)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	// 4. Create Company
	var createCompany struct {
		InsertCompaniesOne struct {
			ID string `json:"id"`
		} `json:"insert_companies_one"`
	}
	err = r.HasuraClient.Request(`
		mutation CreateCompany($name: String!, $licenseKey: String!) {
			insert_companies_one(object: {
				name: $name,
				license_key: $licenseKey,
				max_projects: 5
			}) {
				id
			}
		}
	`, map[string]interface{}{"name": companyName, "licenseKey": licenseKey}, &createCompany)
	if err != nil {
		return nil, fmt.Errorf("failed to create company: %w", err)
	}
	companyID := createCompany.InsertCompaniesOne.ID

	// 5. Create User
	var createUser struct {
		InsertUsersOne struct {
			ID string `json:"id"`
		} `json:"insert_users_one"`
	}
	createUserVars := map[string]interface{}{
		"email":        adminEmail,
		"passwordHash": passwordHash,
		"companyId":    companyID,
		"fullName":     fullName,
	}
	err = r.HasuraClient.Request(`
		mutation CreateUser($email: String!, $passwordHash: String!, $companyId: uuid!, $fullName: String) {
			insert_users_one(object: {
				email: $email,
				password_hash: $passwordHash,
				company_id: $companyId,
				full_name: $fullName
			}) {
				id
			}
		}
	`, createUserVars, &createUser)
	if err != nil {
		// Rollback company? Ideally yes. But simple impl for now.
		return nil, fmt.Errorf("failed to create user: %w", err)
	}
	userID := createUser.InsertUsersOne.ID

	// 6. Update Company Admin
	var updateCompany struct {
		UpdateCompaniesByPk struct {
			ID string `json:"id"`
		} `json:"update_companies_by_pk"`
	}
	err = r.HasuraClient.Request(`
		mutation UpdateCompanyAdmin($id: uuid!, $adminId: uuid!) {
			update_companies_by_pk(pk_columns: {id: $id}, _set: {admin_user_id: $adminId}) {
				id
			}
		}
	`, map[string]interface{}{"id": companyID, "adminId": userID}, &updateCompany)
	if err != nil {
		return nil, fmt.Errorf("failed to update company admin: %w", err)
	}

	userIDUUID, _ := uuid.Parse(userID)
	token, err := auth.GenerateJWT(userIDUUID, []string{"user", "admin"}, "admin")
	if err != nil {
		return nil, err
	}

	return &model.SignupResponse{
		Token: token,
		User: &model.User{
			ID:        userID,
			Email:     adminEmail,
			FullName:  fullName,
			CompanyID: companyID,
		},
		Company: &model.Company{
			ID:   companyID,
			Name: companyName,
		},
	}, nil
}

// AddUser is the resolver for the addUser field.
func (r *mutationResolver) AddUser(ctx context.Context, email string, password string, fullName *string, companyID string) (*model.User, error) {
	// 1. Check if email already exists
	var checkEmail struct {
		Users []struct {
			ID string `json:"id"`
		} `json:"users"`
	}
	err := r.HasuraClient.Request(`
		query CheckEmail($email: String!) {
			users(where: {email: {_eq: $email}}) { id }
		}
	`, map[string]interface{}{"email": email}, &checkEmail)
	if err != nil {
		return nil, err
	}
	if len(checkEmail.Users) > 0 {
		return nil, errors.New("Email already registered")
	}

	// 2. Hash Password
	passwordHash, err := auth.HashPassword(password)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	// 3. Create User
	var createUser struct {
		InsertUsersOne struct {
			ID       string  `json:"id"`
			Email    string  `json:"email"`
			FullName *string `json:"full_name"`
		} `json:"insert_users_one"`
	}
	createUserVars := map[string]interface{}{
		"email":        email,
		"passwordHash": passwordHash,
		"companyId":    companyID,
		"fullName":     fullName,
	}
	err = r.HasuraClient.Request(`
		mutation CreateUser($email: String!, $passwordHash: String!, $companyId: uuid!, $fullName: String) {
			insert_users_one(object: {
				email: $email,
				password_hash: $passwordHash,
				company_id: $companyId,
				full_name: $fullName
			}) {
				id
				email
				full_name
			}
		}
	`, createUserVars, &createUser)
	if err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	return &model.User{
		ID:        createUser.InsertUsersOne.ID,
		Email:     createUser.InsertUsersOne.Email,
		FullName:  createUser.InsertUsersOne.FullName,
		CompanyID: companyID,
	}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
