version: "3"
services:
  backend:
    image: git-analytics/backend
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/app:/app
  frontend:
    image: git-analytics/frontend
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/angular-app:/src/angular-app
      - /src/angular-app/node_modules
  proxy:
    image: git-analytics/proxy:latest
    depends_on:
     - frontend
     - backend
    ports:
      - "80:80"

networks:
  capstone-website40_default:
    external: true
