// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AssignMemberInput struct {
	ProjectID string            `json:"projectId"`
	UserID    string            `json:"userId"`
	Role      ProjectMemberRole `json:"role"`
}

type Company struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateProjectInput struct {
	Name          string  `json:"name"`
	ManagerUserID string  `json:"managerUserId"`
	Description   *string `json:"description,omitempty"`
	RepoURL       *string `json:"repoUrl,omitempty"`
}

type DeleteProjectInput struct {
	ProjectID string `json:"projectId"`
}

type DeleteProjectResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type LoginResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type Project struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	CompanyID     string  `json:"companyId"`
	ManagerUserID string  `json:"managerUserId"`
	Description   *string `json:"description,omitempty"`
	RepoURL       *string `json:"repoUrl,omitempty"`
	CreatedAt     string  `json:"createdAt"`
}

type ProjectMember struct {
	ID        string            `json:"id"`
	ProjectID string            `json:"projectId"`
	UserID    string            `json:"userId"`
	Role      ProjectMemberRole `json:"role"`
	JoinedAt  string            `json:"joinedAt"`
}

type Query struct {
}

type SignupResponse struct {
	Token   string   `json:"token"`
	User    *User    `json:"user"`
	Company *Company `json:"company"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	FullName  *string `json:"fullName,omitempty"`
	CompanyID string  `json:"companyId"`
}

type ProjectMemberRole string

const (
	ProjectMemberRoleDeveloper ProjectMemberRole = "DEVELOPER"
	ProjectMemberRoleGuest     ProjectMemberRole = "GUEST"
)

var AllProjectMemberRole = []ProjectMemberRole{
	ProjectMemberRoleDeveloper,
	ProjectMemberRoleGuest,
}

func (e ProjectMemberRole) IsValid() bool {
	switch e {
	case ProjectMemberRoleDeveloper, ProjectMemberRoleGuest:
		return true
	}
	return false
}

func (e ProjectMemberRole) String() string {
	return string(e)
}

func (e *ProjectMemberRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectMemberRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectMemberRole", str)
	}
	return nil
}

func (e ProjectMemberRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectMemberRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectMemberRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
