"""add isAdmin to User

Revision ID: 1bb14dd270b7
Revises: 2e3cb8764e29
Create Date: 2023-09-22 18:55:13.218009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb14dd270b7'
down_revision: Union[str, None] = '2e3cb8764e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'status')
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.add_column('project', sa.Column('status', sa.VARCHAR(length=8), nullable=True))
    # ### end Alembic commands ###
