"""Add projectStatus

Revision ID: 2e3cb8764e29
Revises: ae27518f3256
Create Date: 2023-08-23 15:25:01.686360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3cb8764e29'
down_revision: Union[str, None] = 'ae27518f3256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='projectstatus', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
