"""Update project table

Revision ID: 6f041a0d502b
Revises: 9d109452566f
Create Date: 2024-08-16 15:18:41.102301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f041a0d502b'
down_revision: Union[str, None] = '9d109452566f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('lastScanned', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'lastScanned')
    op.drop_column('project', 'rating')
    # ### end Alembic commands ###
