"""first revision





Revision ID: ae27518f3256


Revises: 


Create Date: 2023-08-22 09:37:44.045999





"""


from typing import Sequence, Union





from alembic import op


import sqlalchemy as sa








# revision identifiers, used by Alembic.


revision: str = 'ae27518f3256'


down_revision: Union[str, None] = None


branch_labels: Union[str, Sequence[str], None] = None


depends_on: Union[str, Sequence[str], None] = None








def upgrade() -> None:


    # ### commands auto generated by Alembic - please adjust! ###


    op.create_table('company',


    sa.Column('id', sa.Integer(), nullable=False),


    sa.Column('name', sa.String(), nullable=True),


    sa.Column('created', sa.DateTime(), nullable=True),


    sa.Column('serial', sa.String(), nullable=True),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_table('project',


    sa.Column('id', sa.Integer(), nullable=False),


    sa.Column('title', sa.String(), nullable=True),


    sa.Column('description', sa.String(), nullable=True),


    sa.Column('company_id', sa.Integer(), nullable=True),


    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_table('user',


    sa.Column('id', sa.Integer(), nullable=False),


    sa.Column('name', sa.String(), nullable=True),


    sa.Column('username', sa.String(), nullable=True),


    sa.Column('email', sa.String(), nullable=True),


    sa.Column('password', sa.String(), nullable=True),


    sa.Column('user_type', sa.Enum('USER', 'SUPER', 'DEMO', name='usertype', native_enum=False), nullable=True),


    sa.Column('is_active', sa.Boolean(), nullable=True),


    sa.Column('company_id', sa.Integer(), nullable=True),


    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)


    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)


    op.create_table('task',


    sa.Column('id', sa.Integer(), nullable=False),


    sa.Column('created', sa.DateTime(), nullable=True),


    sa.Column('type', sa.Enum('STYLE', 'RETRIEVE', name='tasktype', native_enum=False), nullable=True),


    sa.Column('status', sa.Enum('NOT_STARTED', 'RUNNING', 'PROCESSING', 'STOPPED', 'FINISHED', 'ERROR', name='taskstatus', native_enum=False), nullable=True),


    sa.Column('updated', sa.DateTime(), nullable=True),


    sa.Column('project_id', sa.Integer(), nullable=True),


    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index(op.f('ix_task_created'), 'task', ['created'], unique=False)


    op.create_table('uproj',


    sa.Column('id', sa.Integer(), nullable=False),


    sa.Column('joined', sa.DateTime(), nullable=True),


    sa.Column('proj_id', sa.Integer(), nullable=True),


    sa.Column('user_id', sa.Integer(), nullable=True),


    sa.Column('access', sa.Enum('ADMIN', 'MANAGER', 'READ_WRITE', 'GUEST', name='projectaccess', native_enum=False), nullable=True),


    sa.ForeignKeyConstraint(['proj_id'], ['project.id'], ),


    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index(op.f('ix_uproj_joined'), 'uproj', ['joined'], unique=False)


    # ### end Alembic commands ###








def downgrade() -> None:


    # ### commands auto generated by Alembic - please adjust! ###


    op.drop_index(op.f('ix_uproj_joined'), table_name='uproj')


    op.drop_table('uproj')


    op.drop_index(op.f('ix_task_created'), table_name='task')


    op.drop_table('task')


    op.drop_index(op.f('ix_user_username'), table_name='user')


    op.drop_index(op.f('ix_user_email'), table_name='user')


    op.drop_table('user')


    op.drop_table('project')


    op.drop_table('company')


    # ### end Alembic commands ###


