version: "3.3"
services:
  backendbuilder:
    image: git-analytics/backendbuilder:latest
    build: backend
  frontendbuilder:
    image: git-analytics/frontendbuilder:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
  proxybuilder:
    image: git-analytics/proxy:latest
    build:
      context: .
      dockerfile: Dockerfile.proxy
  binarybuilder:
    image: git-analytics/binarybuilder:latest
    build: binary
  postgres:
    image: git-analytics/postgres:latest
    build:
      context: .
      dockerfile: Dockerfile.postgres
