version: "3"
services:
  backendbuilder:
    image: git-analytics/backendbuilder:latest
    build: backend
  frontendbuilder:
    image: git-analytics/frontendbuilder:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
  proxybuilder:
    image: git-analytics/proxybuilder:latest
    build:
      context: .
      dockerfile: Dockerfile.proxy
  # binarybuilder:
  #   image: git-analytics/binarybuilder:latest
  #   build: binary